title: "SKiev"
description: "Персональный блог и портфолио Славы Киевского"
favicon: /favicon.ico
url: https://slavakievsky.github.io
editurl: https://github.com/slavakievsky/slavakievsky.github.io/blob/master
baseurl: /
lang: ru
lang-utf: ru_RU



collections:
  posts:
    output: true
    permalink: /blog/:title/
  cases:
    output: true
    permalink: /cases/:title/
    sort_by: date
  case-categories:
    output: true
    permalink: /case-categories/:title/
  pets:
    output: true
    permalink: /pets/:title/
    sort_by: date
  drafts:
    output: true
    permalink: /drafts/:title/
  categories:
    output: true
    permalink: /categories/:title/
  knowledgebase:
    output: true
    permalink: /knowledgebase/:categories/:title/
  knowledgebase-categories:
    output: true
    premalink: /knowledgebase/categories/:title/

paginate: 4
paginate_path: /blog/page:num

feed:
  collections:
    - posts
    - pets
    - cases

markdown: kramdown
highlighter: rouge
kramdown:
  smart_quotes: apos,apos,quot,quot
  typographic_symbols: {hellip: ...}
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
      block:
        line_numbers: true
        start_line: 1

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - _site
  - .jekyll-metadata
  - .jekyll-cache

sass:
  style: compressed
  load_paths:
    - _sass

webmaster-verifications:
  yandex: "bcd4d2d2d56f4722"
  google: "OZwmnQADLPoNODcFwqfbAlxJ4be5VbCysIsXDkmBiYY"